# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0002_auto_20161208_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad_apoyo',
            name='ubicacion_actividad',
            field=models.CharField(default='aqui', max_length=150),
            preserve_default=False,
        ),
    ]
