# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 04:57
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapituloLibro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='titulo', unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('pagina_inicio', models.PositiveIntegerField()),
                ('pagina_fin', models.PositiveIntegerField()),
                ('agradecimientos', models.ManyToManyField(related_name='capitulo_libro_agradecimientos', to=settings.AUTH_USER_MODEL)),
                ('autores', models.ManyToManyField(related_name='capitulo_libro_autores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['libro', 'titulo'],
                'verbose_name': 'Capítulo de libro',
                'verbose_name_plural': 'Capítulos de libros',
                'get_latest_by': ['fecha', 'libro', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coleccion', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='coleccion', unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['coleccion'],
                'verbose_name': 'Colección',
                'verbose_name_plural': 'Colecciones',
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editorial', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='editorial', unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['editorial'],
                'verbose_name_plural': 'Editoriales',
            },
        ),
        migrations.CreateModel(
            name='Indice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='indice', unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['indice'],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_libro', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='libro', unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('numero_edicion', models.PositiveIntegerField(default=1)),
                ('numero_paginas', models.PositiveIntegerField(default=0)),
                ('volumen', models.CharField(blank=True, max_length=255)),
                ('isbn', models.SlugField(max_length=30)),
                ('url', models.URLField(blank=True)),
                ('autores', models.ManyToManyField(related_name='libro_autores', to=settings.AUTH_USER_MODEL)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Ciudad')),
                ('coleccion', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='publicacion.Coleccion')),
                ('coordinadores', models.ManyToManyField(blank=True, related_name='libro_coordinadores', to=settings.AUTH_USER_MODEL)),
                ('editores', models.ManyToManyField(blank=True, related_name='libro_editores', to=settings.AUTH_USER_MODEL)),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicacion.Editorial')),
            ],
            options={
                'ordering': ['nombre_libro'],
                'get_latest_by': ['fecha', 'nombre_libro', 'editorial'],
            },
        ),
        migrations.CreateModel(
            name='Memoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memoria', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='memoria')),
            ],
        ),
        migrations.CreateModel(
            name='PrologoLibro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='libro', unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('pagina_inicio', models.PositiveIntegerField()),
                ('pagina_fin', models.PositiveIntegerField()),
                ('agradecimientos', models.ManyToManyField(related_name='prologo_libro_agradecimientos', to=settings.AUTH_USER_MODEL)),
                ('autores', models.ManyToManyField(related_name='prologo_libro_autores', to=settings.AUTH_USER_MODEL)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicacion.Libro')),
            ],
            options={
                'ordering': ['libro'],
                'verbose_name': 'Prólogo de libro',
                'verbose_name_plural': 'Prólogos de libros',
                'get_latest_by': ['fecha', 'libro'],
            },
        ),
        migrations.CreateModel(
            name='ResenaLibro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='libro', unique=True)),
                ('fecha', models.DateField()),
                ('pagina_inicio', models.PositiveIntegerField()),
                ('pagina_fin', models.PositiveIntegerField()),
                ('agradecimientos', models.ManyToManyField(related_name='resena_libro_agradecimientos', to=settings.AUTH_USER_MODEL)),
                ('autores', models.ManyToManyField(related_name='resena_libro_autores', to=settings.AUTH_USER_MODEL)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicacion.Libro')),
            ],
            options={
                'ordering': ['libro'],
                'verbose_name': 'Reseña de libro',
                'verbose_name_plural': 'Reseñas de libros',
                'get_latest_by': ['fecha', 'libro'],
            },
        ),
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_revista', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='revista', unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicacion.Editorial')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Pais')),
                ('tags', models.ManyToManyField(blank=True, related_name='revista_tags', to='nucleo.Tag')),
            ],
            options={
                'ordering': ['nombre_revista'],
                'get_latest_by': ['fecha', 'nombre_revista', 'editorial'],
            },
        ),
        migrations.CreateModel(
            name='StatusPublicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='status', unique=True)),
            ],
            options={
                'verbose_name': 'Status de publicacion',
                'verbose_name_plural': 'Status de publicaciones',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='tipo', unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['tipo'],
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documentos',
            },
        ),
        migrations.AddField(
            model_name='libro',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicacion.StatusPublicacion'),
        ),
        migrations.AddField(
            model_name='libro',
            name='tags',
            field=models.ManyToManyField(related_name='libro_tags', to='nucleo.Tag'),
        ),
        migrations.AddField(
            model_name='capitulolibro',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicacion.Libro'),
        ),
    ]
