# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 21:22
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapituloLibro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capitulo', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('pagina_inicio', models.PositiveIntegerField()),
                ('pagina_fin', models.PositiveIntegerField()),
                ('agradecimientos', models.ManyToManyField(related_name='capitulo_libro_agradecimientos', to=settings.AUTH_USER_MODEL)),
                ('autores', models.ManyToManyField(related_name='capitulo_libro_autores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Capítulos de libros',
                'verbose_name': 'Capítulo de libro',
                'ordering': ['libro', 'capitulo'],
                'get_latest_by': ['fecha', 'libro', 'capitulo'],
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editorial', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='editorial', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Editoriales',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro', models.CharField(max_length=255, unique=True)),
                ('fecha', models.DateField()),
                ('url', models.URLField(blank=True)),
                ('isbn', models.SlugField(max_length=17)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='libro', unique=True)),
                ('autores', models.ManyToManyField(related_name='libro_autores', to=settings.AUTH_USER_MODEL)),
                ('editores', models.ManyToManyField(related_name='libro_editores', to=settings.AUTH_USER_MODEL)),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicacion.Editorial')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Pais')),
            ],
            options={
                'ordering': ['libro'],
                'get_latest_by': ['fecha', 'libro', 'editorial'],
            },
        ),
        migrations.CreateModel(
            name='PrologoLibro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('pagina_inicio', models.PositiveIntegerField()),
                ('pagina_fin', models.PositiveIntegerField()),
                ('agradecimientos', models.ManyToManyField(related_name='prologo_libro_agradecimientos', to=settings.AUTH_USER_MODEL)),
                ('autores', models.ManyToManyField(related_name='prologo_libro_autores', to=settings.AUTH_USER_MODEL)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicacion.Libro')),
            ],
            options={
                'verbose_name_plural': 'Próologos de libros',
                'verbose_name': 'Próologo de libro',
                'ordering': ['libro'],
                'get_latest_by': ['fecha', 'libro'],
            },
        ),
        migrations.CreateModel(
            name='ResenaLibro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('pagina_inicio', models.PositiveIntegerField()),
                ('pagina_fin', models.PositiveIntegerField()),
                ('agradecimientos', models.ManyToManyField(related_name='resena_libro_agradecimientos', to=settings.AUTH_USER_MODEL)),
                ('autores', models.ManyToManyField(related_name='resena_libro_autores', to=settings.AUTH_USER_MODEL)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicacion.Libro')),
            ],
            options={
                'verbose_name_plural': 'Reseñas de libros',
                'verbose_name': 'Reseña de libro',
                'ordering': ['libro'],
                'get_latest_by': ['fecha', 'libro'],
            },
        ),
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revista', models.CharField(max_length=255, unique=True)),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('fecha', models.DateField()),
                ('url', models.URLField(blank=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='libro', unique=True)),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicacion.Editorial')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Pais')),
            ],
            options={
                'ordering': ['revista'],
                'get_latest_by': ['fecha', 'revista', 'editorial'],
            },
        ),
        migrations.CreateModel(
            name='StatusPublicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='status', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Status de publicaciones',
                'verbose_name': 'Status de publicacion',
            },
        ),
        migrations.AddField(
            model_name='revista',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicacion.StatusPublicacion'),
        ),
        migrations.AddField(
            model_name='revista',
            name='tags',
            field=models.ManyToManyField(related_name='revista_tags', to='nucleo.Tag'),
        ),
        migrations.AddField(
            model_name='libro',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicacion.StatusPublicacion'),
        ),
        migrations.AddField(
            model_name='libro',
            name='tags',
            field=models.ManyToManyField(related_name='libro_tags', to='nucleo.Tag'),
        ),
        migrations.AddField(
            model_name='capitulolibro',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicacion.Libro'),
        ),
    ]
