# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prologolibro',
            options={'get_latest_by': ['fecha', 'libro'], 'ordering': ['libro'], 'verbose_name': 'Prólogo de libro', 'verbose_name_plural': 'Prólogos de libros'},
        ),
    ]
