# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0002_auto_20161215_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='revista',
            name='issn',
            field=models.SlugField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.SlugField(max_length=20),
        ),
    ]
