# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 05:07
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleo', '0005_auto_20161215_2033'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaConocimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_conocimiento', models.CharField(max_length=255, unique=True, verbose_name='Área de conocimiento')),
                ('descripcion', models.TextField(blank=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='area_conocimiento', unique=True)),
            ],
            options={
                'verbose_name': 'Área de conocimiento',
                'ordering': ['area_conocimiento'],
                'verbose_name_plural': 'Áreas de conocimiento',
            },
        ),
        migrations.CreateModel(
            name='AreaEspecializacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_especializacion', models.CharField(max_length=255, unique=True, verbose_name='Área de conocimiento')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripición')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='area_especializacion', unique=True)),
            ],
            options={
                'verbose_name': 'Área de especialización',
                'ordering': ['area_especializacion'],
                'verbose_name_plural': 'Áreas de especialización',
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='carrera', unique=True)),
            ],
            options={
                'verbose_name': 'carrera',
                'ordering': ['carrera'],
            },
        ),
        migrations.CreateModel(
            name='CursoEspecializacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripición')),
                ('inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fin', models.DateField(blank=True, verbose_name='Fecha de finalización')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='curso', unique=True)),
                ('area_especializacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formacion_academica.AreaEspecializacion', verbose_name='Área de especialización')),
                ('instituciones', models.ManyToManyField(related_name='cursos_especializacion', to='nucleo.Dependencia')),
                ('instructores', models.ManyToManyField(related_name='cursos_especializacion', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='cursos_especializacion', to='nucleo.Tag')),
            ],
            options={
                'verbose_name': 'Curso de especialización',
                'ordering': ['area_especializacion', 'curso', 'inicio'],
                'verbose_name_plural': 'Cursos de especialización',
            },
        ),
        migrations.CreateModel(
            name='Licenciatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tesis', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio de licenciatura')),
                ('fecha_fin', models.DateField(blank=True, verbose_name='Fecha de terminación de licenciatura')),
                ('fecha_grado', models.DateField(blank=True, verbose_name='Fecha de obtención de grado')),
                ('agradecimientos', models.ManyToManyField(blank=True, related_name='licenciaturas', to=settings.AUTH_USER_MODEL)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formacion_academica.Carrera')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Institucion')),
            ],
            options={
                'ordering': ['fecha_grado', 'carrera'],
            },
        ),
        migrations.CreateModel(
            name='Maestria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tesis', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio de licenciatura')),
                ('fecha_fin', models.DateField(blank=True, verbose_name='Fecha de terminación de licenciatura')),
                ('fecha_grado', models.DateField(blank=True, verbose_name='Fecha de obtención de grado')),
                ('agradecimientos', models.ManyToManyField(blank=True, related_name='maestrias', to=settings.AUTH_USER_MODEL)),
                ('area_conocimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formacion_academica.AreaConocimiento', verbose_name='Área de conocimiento')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Institucion')),
            ],
            options={
                'ordering': ['fecha_grado', 'tesis'],
            },
        ),
        migrations.CreateModel(
            name='TipoCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255, unique=True, verbose_name='Tipo de curso')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripición')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='tipo', unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de curso',
                'ordering': ['tipo'],
                'verbose_name_plural': 'Tipos de cursos',
            },
        ),
        migrations.AddField(
            model_name='cursoespecializacion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formacion_academica.TipoCurso'),
        ),
        migrations.AddField(
            model_name='cursoespecializacion',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Ubicacion', verbose_name='Ubicación'),
        ),
        migrations.AlterUniqueTogether(
            name='cursoespecializacion',
            unique_together=set([('area_especializacion', 'curso', 'inicio')]),
        ),
    ]
