# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 00:31
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleo', '0004_auto_20161214_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaEspecializacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_especializacion', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='area_especializacion', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CursoEspecializacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('curso_inicio', models.DateField()),
                ('curso_fin', models.DateField(blank=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='curso', unique=True)),
                ('area_especializacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formacion_academica.AreaEspecializacion')),
                ('instituciones', models.ManyToManyField(related_name='cursos_especializacion', to='nucleo.Dependencia')),
            ],
            options={
                'verbose_name_plural': 'Cursos de especialización',
                'verbose_name': 'Curso de especialización',
            },
        ),
        migrations.CreateModel(
            name='TipoCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='tipo', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='cursoespecializacion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formacion_academica.TipoCurso'),
        ),
        migrations.AddField(
            model_name='cursoespecializacion',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Ubicacion'),
        ),
        migrations.AlterUniqueTogether(
            name='cursoespecializacion',
            unique_together=set([('curso', 'curso_inicio')]),
        ),
    ]
