# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 00:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formacion_academica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaespecializacion',
            options={'verbose_name': 'Área de especialización', 'verbose_name_plural': 'Áreas de especialización'},
        ),
        migrations.AlterModelOptions(
            name='tipocurso',
            options={'verbose_name': 'Tipo de curso', 'verbose_name_plural': 'Tipos de cursos'},
        ),
        migrations.AddField(
            model_name='cursoespecializacion',
            name='instructores',
            field=models.ManyToManyField(related_name='cursos_especializacion', to=settings.AUTH_USER_MODEL),
        ),
    ]
