# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_auto_20161214_2151'),
        ('formacion_academica', '0002_auto_20161215_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursoespecializacion',
            name='tags',
            field=models.ManyToManyField(related_name='cursos_especializacion', to='nucleo.Tag'),
        ),
        migrations.AlterField(
            model_name='areaespecializacion',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tipocurso',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
