# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacion_academica', '0003_auto_20161215_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursoespecializacion',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cursoespecializacion',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='cursos_especializacion', to='nucleo.Tag'),
        ),
    ]
