# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 02:33
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nucleo', '0005_auto_20161215_2033'),
        ('formacion_academica', '0004_auto_20161215_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='carrera', unique=True)),
            ],
            options={
                'verbose_name': 'carrera',
                'ordering': ['carrera'],
            },
        ),
        migrations.CreateModel(
            name='Licenciatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tesis', models.CharField(max_length=255)),
                ('fecha_grado', models.DateField(verbose_name='Fecha de obtención de grado')),
                ('agradecimientos', models.ManyToManyField(blank=True, related_name='licenciaturas', to=settings.AUTH_USER_MODEL)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formacion_academica.Carrera')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Institucion')),
            ],
        ),
        migrations.AlterModelOptions(
            name='areaespecializacion',
            options={'ordering': ['area_especializacion'], 'verbose_name': 'Área de especialización', 'verbose_name_plural': 'Áreas de especialización'},
        ),
        migrations.AlterModelOptions(
            name='cursoespecializacion',
            options={'ordering': ['area_especializacion', 'curso', 'curso_inicio'], 'verbose_name': 'Curso de especialización', 'verbose_name_plural': 'Cursos de especialización'},
        ),
        migrations.AlterModelOptions(
            name='tipocurso',
            options={'ordering': ['tipo'], 'verbose_name': 'Tipo de curso', 'verbose_name_plural': 'Tipos de cursos'},
        ),
        migrations.AlterUniqueTogether(
            name='cursoespecializacion',
            unique_together=set([('area_especializacion', 'curso', 'curso_inicio')]),
        ),
    ]
