# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 03:21
from __future__ import unicode_literals

from django.db import migrations, models
from datetime import date


class Migration(migrations.Migration):

    dependencies = [
        ('formacion_academica', '0005_auto_20161215_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenciatura',
            name='fin',
            field=models.DateField(blank=True, default=date(2015, 1, 1), verbose_name='Fecha de terminación de licenciatura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licenciatura',
            name='inicio',
            field=models.DateField(default=date(2015, 1, 1), verbose_name='Fecha de inicio de licenciatura'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='licenciatura',
            name='fecha_grado',
            field=models.DateField(blank=True, verbose_name='Fecha de obtención de grado'),
        ),
    ]
