# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='institucion',
        ),
        migrations.AlterField(
            model_name='cargo',
            name='cargo',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
