# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 03:13
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='direccion1', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='ubicacion',
            unique_together=set([('direccion1', 'direccion2', 'telefono')]),
        ),
    ]
