# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_auto_20161212_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nucleo.Pais'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='codigo_postal',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='ciudad',
            unique_together=set([('ciudad', 'estado', 'pais')]),
        ),
    ]
