# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 03:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nucleo', '0002_auto_20161212_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoAsignado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_inicio', models.DateField()),
                ('cargo_fin', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='cargo',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='cargoasignado',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Cargo'),
        ),
        migrations.AddField(
            model_name='cargoasignado',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
