# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_auto_20161212_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='ciudad',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='estado',
            name='estado',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='estado',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
