# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_auto_20161212_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargoasignado',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='cargoasignado',
            name='user',
        ),
        migrations.DeleteModel(
            name='CargoAsignado',
        ),
    ]
