# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 03:51
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_auto_20161213_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='direccion1', unique=True),
        ),
    ]
