# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_auto_20161212_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'ordering': ['ciudad'], 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'ordering': ['estado']},
        ),
        migrations.AlterModelOptions(
            name='institucion',
            options={'verbose_name_plural': 'Instituciones'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ['pais'], 'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'verbose_name_plural': 'Ubicaciones'},
        ),
    ]
