# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_auto_20161214_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependencia',
            options={'ordering': ['dependencia']},
        ),
        migrations.AlterModelOptions(
            name='institucion',
            options={'ordering': ['institucion'], 'verbose_name': 'Institución', 'verbose_name_plural': 'Instituciones'},
        ),
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'ordering': ['ciudad', 'direccion1'], 'verbose_name': 'Ubicación', 'verbose_name_plural': 'Ubicaciones'},
        ),
        migrations.AddField(
            model_name='cargo',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
