# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0005_auto_20161212_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'ordering': ['estado', 'ciudad'], 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'ordering': ['pais', 'estado']},
        ),
        migrations.AddField(
            model_name='dependencia',
            name='slug',
            field=models.SlugField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='ciudad',
            unique_together=set([('ciudad', 'slug', 'estado', 'pais')]),
        ),
        migrations.AlterUniqueTogether(
            name='dependencia',
            unique_together=set([('dependencia', 'slug', 'institucion')]),
        ),
        migrations.AlterUniqueTogether(
            name='estado',
            unique_together=set([('estado', 'slug', 'pais')]),
        ),
        migrations.AlterUniqueTogether(
            name='ubicacion',
            unique_together=set([('direccion1', 'direccion2', 'slug', 'ciudad', 'estado', 'pais')]),
        ),
    ]
