# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 04:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0005_comisionacademica_comisionevaluacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comisionacademica',
            options={'verbose_name_plural': 'Comisiones de académicas'},
        ),
        migrations.AlterModelOptions(
            name='comisionevaluacion',
            options={'verbose_name_plural': 'Comisiones de evaluación'},
        ),
    ]
