# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0006_auto_20161212_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='fecha_edicion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='fecha_edicion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='estado',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='estado',
            name='fecha_edicion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='fecha_edicion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pais',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pais',
            name='fecha_edicion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='fecha_edicion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='fecha_edicion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
