# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0007_auto_20161212_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciudad',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='fecha_edicion',
        ),
        migrations.RemoveField(
            model_name='dependencia',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='dependencia',
            name='fecha_edicion',
        ),
        migrations.RemoveField(
            model_name='estado',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='estado',
            name='fecha_edicion',
        ),
        migrations.RemoveField(
            model_name='institucion',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='institucion',
            name='fecha_edicion',
        ),
        migrations.RemoveField(
            model_name='pais',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='pais',
            name='fecha_edicion',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='fecha_edicion',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='fecha_edicion',
        ),
    ]
