# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0008_auto_20161212_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Dependencia')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Institucion')),
            ],
        ),
    ]
