# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 05:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tags', models.ManyToManyField(related_name='actividad', to='nucleo.Tag')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Ubicacion')),
            ],
            options={
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='CargoApoyoInstitucional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255)),
                ('cargo_inicio', models.DateField()),
                ('cargo_fin', models.DateField()),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Cargo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cargos Apoyo Institucional',
            },
        ),
        migrations.CreateModel(
            name='ComisionAcademicaApoyoInstitucional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255)),
                ('comision_academica_inicio', models.DateField()),
                ('comision_academica_fin', models.DateField()),
                ('comision_academica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.ComisionAcademica')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Comisiónes Académicas de Apoyo Institucional',
            },
        ),
        migrations.CreateModel(
            name='ComisionEvaluacionApoyoInstitucional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255)),
                ('comision_evaluacion_inicio', models.DateField()),
                ('comision_evaluacion_fin', models.DateField()),
                ('comision_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.ComisionEvaluacion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Comisiónes de Evaluación de Apoyo Institucional',
            },
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255)),
                ('cargo_inicio', models.DateField()),
                ('cargo_fin', models.DateField()),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Cargo')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Entidad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Representantes Apoyo Institucional',
            },
        ),
    ]
