# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_edicion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_edicion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_edicion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_edicion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='dependencia',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apoyo_institucional.Institucion'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apoyo_institucional.Dependencia'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apoyo_institucional.Institucion'),
        ),
    ]
