# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 04:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_auto_20161212_2204'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apoyo_institucional', '0002_auto_20161212_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoApoyoInstitucional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_inicio', models.DateField()),
                ('cargo_fin', models.DateField()),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Cargo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cargos Apoyo Institucional',
            },
        ),
    ]
