# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 04:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apoyo_institucional', '0003_cargoapoyoinstitucional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comisionacademica',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='comisionacademica',
            name='dependencia',
        ),
        migrations.RemoveField(
            model_name='comisionacademica',
            name='institucion',
        ),
        migrations.DeleteModel(
            name='ComisionAcademica',
        ),
    ]
