# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 00:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apoyo_institucional', '0004_cargo_dependencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='dependencia',
        ),
    ]
