# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 04:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nucleo', '0006_auto_20161212_2224'),
        ('apoyo_institucional', '0004_auto_20161212_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComisionAcademicaApoyoInstitucional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comision_academica_inicio', models.DateField()),
                ('comision_academica_fin', models.DateField()),
                ('comision_academica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Cargo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Comisiónes Académicas de Apoyo Institucional',
            },
        ),
        migrations.CreateModel(
            name='ComisionEvaluacionApoyoInstitucional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comision_evaluacion_inicio', models.DateField()),
                ('comision_evaluacion_fin', models.DateField()),
                ('comision_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Cargo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Comisiónes Académicas de Apoyo Institucional',
            },
        ),
    ]
