# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apoyo_institucional', '0005_comisionacademicaapoyoinstitucional_comisionevaluacionapoyoinstitucional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comisionevaluacionapoyoinstitucional',
            options={'verbose_name_plural': 'Comisiónes de Evaluación de Apoyo Institucional'},
        ),
        migrations.AlterField(
            model_name='comisionacademicaapoyoinstitucional',
            name='comision_academica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.ComisionAcademica'),
        ),
        migrations.AlterField(
            model_name='comisionevaluacionapoyoinstitucional',
            name='comision_evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.ComisionEvaluacion'),
        ),
    ]
