# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apoyo_institucional', '0005_remove_cargo_dependencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='dependencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apoyo_institucional.Dependencia'),
            preserve_default=False,
        ),
    ]
