# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_auto_20161212_1457'),
        ('apoyo_institucional', '0006_cargo_dependencia'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dependencia',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='dependencia',
            name='institucion',
        ),
        migrations.AddField(
            model_name='actividad',
            name='tags',
            field=models.ManyToManyField(related_name='blog_posts', to='nucleo.Tag'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Dependencia'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Institucion'),
        ),
        migrations.DeleteModel(
            name='Dependencia',
        ),
        migrations.DeleteModel(
            name='Institucion',
        ),
    ]
