# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyo_institucional', '0007_auto_20161212_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='fecha_edicion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='fecha_edicion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='fecha_fin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
    ]
