# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apoyo_institucional', '0008_auto_20161212_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='fecha_edicion',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='fecha_edicion',
        ),
    ]
