# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoyo_institucional', '0010_auto_20161212_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='nombre',
            new_name='actividad',
        ),
        migrations.RenameField(
            model_name='cargo',
            old_name='nombre_cargo',
            new_name='cargo',
        ),
        migrations.AlterField(
            model_name='actividad',
            name='tags',
            field=models.ManyToManyField(related_name='actividad', to='nucleo.Tag'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='fecha_inicio',
            field=models.DateField(),
        ),
    ]
