# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 06:20
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloMemoriaCongreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descipcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('pagina_inicio', models.PositiveIntegerField()),
                ('pagina_fin', models.PositiveIntegerField()),
                ('issn', models.SlugField(max_length=20)),
                ('vinculo', models.CharField(default='Este no se como se usa, estaba en las tablas', max_length=255)),
                ('agradecimientos', models.ManyToManyField(blank=True, related_name='articulo_memoria_congreso_agradecimientos', to=settings.AUTH_USER_MODEL)),
                ('autores_adscritos', models.ManyToManyField(related_name='articulo_memoria_congreso_autores_adscritos', to=settings.AUTH_USER_MODEL)),
                ('autores_externos', models.ManyToManyField(related_name='articulo_memoria_congreso_autores_externos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Artículos en extenso en memorias de congresos',
                'verbose_name': 'Artículo en extenso en memoria de congreso',
            },
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='editor')),
            ],
        ),
        migrations.CreateModel(
            name='Indice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='indice')),
            ],
        ),
        migrations.CreateModel(
            name='Memoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memoria', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='memoria')),
            ],
        ),
        migrations.AddField(
            model_name='articulomemoriacongreso',
            name='editores',
            field=models.ManyToManyField(related_name='articulo_memoria_congreso_editores', to='difusion_cientifica.Editor'),
        ),
        migrations.AddField(
            model_name='articulomemoriacongreso',
            name='indices',
            field=models.ManyToManyField(related_name='articulo_memoria_congreso_indices', to='difusion_cientifica.Indice'),
        ),
        migrations.AddField(
            model_name='articulomemoriacongreso',
            name='memoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='difusion_cientifica.Memoria'),
        ),
        migrations.AddField(
            model_name='articulomemoriacongreso',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Pais'),
        ),
        migrations.AddField(
            model_name='articulomemoriacongreso',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.Ubicacion'),
        ),
    ]
