# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('difusion_cientifica', '0002_auto_20161215_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulomemoriacongreso',
            options={'verbose_name': 'Artículo en extenso en memoria de congreso', 'verbose_name_plural': 'Artículos en extenso en memorias de congresos'},
        ),
    ]
