# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 22:50
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesarrolloTecnologico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_desarrollo_tecnologico', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField()),
                ('version', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True)),
                ('fecha', models.DateField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=models.CharField(max_length=255, unique=True), unique=True)),
                ('agradecimientos', models.ManyToManyField(related_name='agradecimiento', to=settings.AUTH_USER_MODEL)),
                ('autores', models.ManyToManyField(related_name='autor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licencia', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=models.CharField(max_length=255, unique=True), unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=models.CharField(max_length=255, unique=True), unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDesarrollo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_desarrollo', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=models.CharField(max_length=255, unique=True), unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='desarrollotecnologico',
            name='licencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desarrollo_tecnologico.Licencia'),
        ),
        migrations.AddField(
            model_name='desarrollotecnologico',
            name='patente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desarrollo_tecnologico.Patente'),
        ),
        migrations.AddField(
            model_name='desarrollotecnologico',
            name='tags',
            field=models.ManyToManyField(related_name='nombre_desarrollo_tecnologico', to='nucleo.Tag'),
        ),
        migrations.AddField(
            model_name='desarrollotecnologico',
            name='tipo_desarrollo_tecnologico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desarrollo_tecnologico.TipoDesarrollo'),
        ),
    ]
