# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 00:35
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleo', '0001_initial'),
        ('publicacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesarrolloTecnologico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_desarrollo_tecnologico', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField()),
                ('version', models.CharField(max_length=100)),
                ('patente', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True)),
                ('fecha', models.DateField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=models.CharField(max_length=255, unique=True), unique=True)),
                ('agradecimientos', models.ManyToManyField(related_name='desarrollo_tecnologico_agradecimientos', to=settings.AUTH_USER_MODEL)),
                ('autores', models.ManyToManyField(related_name='desarrollo_tecnologico_autores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre_desarrollo_tecnologico'],
                'get_latest_by': ['fecha', 'nombre_desarrollo_tecnologico'],
                'verbose_name_plural': 'Desarrollos Tecnológicos',
            },
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licencia', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField()),
                ('url', models.URLField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='licencia', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='proyecto', unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('nombre_wos', models.CharField(max_length=255, unique=True)),
                ('fecha', models.DateField()),
                ('id_doi', models.CharField(max_length=100, unique=True)),
                ('id_wos', models.CharField(max_length=100, unique=True)),
                ('id_isi', models.CharField(max_length=100, unique=True)),
                ('autores', models.ManyToManyField(related_name='proyecto_autores', to=settings.AUTH_USER_MODEL)),
                ('indices', models.ManyToManyField(related_name='proyecto_indices', to='publicacion.Indice')),
            ],
            options={
                'ordering': ['fecha', 'proyecto'],
                'verbose_name_plural': 'Informed técnicod de acceso público',
                'verbose_name': 'Informe técnico de acceso público',
            },
        ),
        migrations.CreateModel(
            name='TipoDesarrollo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_desarrollo', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='tipo_desarrollo', unique=True)),
            ],
            options={
                'ordering': ['tipo_desarrollo'],
                'verbose_name_plural': 'Tipos de desarrollo',
                'verbose_name': 'Tipo de desarrollo',
            },
        ),
        migrations.AddField(
            model_name='desarrollotecnologico',
            name='licencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desarrollo_tecnologico.Licencia'),
        ),
        migrations.AddField(
            model_name='desarrollotecnologico',
            name='proyectos',
            field=models.ManyToManyField(related_name='desarrollo_tecnologico_proyectos', to='desarrollo_tecnologico.Proyecto'),
        ),
        migrations.AddField(
            model_name='desarrollotecnologico',
            name='tags',
            field=models.ManyToManyField(related_name='desarrollo_tecnologico_tags', to='nucleo.Tag'),
        ),
        migrations.AddField(
            model_name='desarrollotecnologico',
            name='tipo_desarrollo_tecnologico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desarrollo_tecnologico.TipoDesarrollo'),
        ),
    ]
