# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 21:22
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo_tecnologico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='proyecto', unique=True)),
            ],
            options={
                'ordering': ['proyecto'],
            },
        ),
        migrations.AlterModelOptions(
            name='desarrollotecnologico',
            options={'get_latest_by': ['fecha', 'nombre_desarrollo_tecnologico'], 'ordering': ['nombre_desarrollo_tecnologico'], 'verbose_name_plural': 'Desarrollos Tecnológicos'},
        ),
        migrations.AlterModelOptions(
            name='tipodesarrollo',
            options={'ordering': ['tipo_desarrollo'], 'verbose_name': 'Tipo de desarrollo', 'verbose_name_plural': 'Tipos de desarrollo'},
        ),
        migrations.AddField(
            model_name='licencia',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licencia',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipodesarrollo',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='desarrollotecnologico',
            name='agradecimientos',
            field=models.ManyToManyField(related_name='desarrollo_tecnologico_agradecimientos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='desarrollotecnologico',
            name='autores',
            field=models.ManyToManyField(related_name='desarrollo_tecnologico_autores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='desarrollotecnologico',
            name='patente',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='desarrollotecnologico',
            name='tags',
            field=models.ManyToManyField(related_name='desarrollo_tecnologico_tags', to='nucleo.Tag'),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='licencia', unique=True),
        ),
        migrations.AlterField(
            model_name='tipodesarrollo',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='tipo_desarrollo', unique=True),
        ),
        migrations.DeleteModel(
            name='Patente',
        ),
        migrations.AddField(
            model_name='desarrollotecnologico',
            name='proyectos',
            field=models.ManyToManyField(related_name='desarrollo_tecnologico_proyectos', to='desarrollo_tecnologico.Proyecto'),
        ),
    ]
